### ISSUE TITLE
All of a sudden getting error when using vim to open files

### ISSUE THREAD

**Issue by ashok-sc** [skwp/dotfiles#793]
When I run (e.g. `vim .zshrc`) I get the following error:

```Error detected while processing /Users/ashokraju/.yadr/vim/bundle/AutoTag/plugin/autotag.vim:
line  229:
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Press ENTER or type command to continue
```

Has anyone else seen this? Randomly started happening today.

**Comment by colinschoen** [comment]
I am getting this too.

**Comment by Lumuy** [comment]
I solved this by reinstall python, then restart your terminal
`brew reinstall python@2`

**Comment by colinschoen** [comment]
Reinstalling python worked.

**Comment by spectralblu** [comment]
Reinstalling python leaves me with the same error.

**Comment by lfilho** [comment]
Assuming this is a non-issue by now
